### ISSUE TITLE
cool!

### ISSUE THREAD

**Issue by aquynh** [syreal17/Cardinal#1]
just found this project, cool! linked to your tool from our website now: http://www.capstone-engine.org/showcase.html

just a question: where is the thesis behind this tool?

keep it up, cheers.

**Comment by syreal17** [comment]
Nguyen, that's great, thanks!

The Capstone version of Cardinal is currently halted because I couldn't create an effective procedure boundary finding algorithm. I switched to IDA which gave that for free. Brumley et al. did some interesting procedure finding work that might enable work on the completely free and open-source version of Cardinal with Capstone to continue. I certainly prefer free and open-source.

I'm waiting to upload the paper to GitHub at least until I submit it to a conference.

Thanks for Capstone! Very elegant, minimalist software

**Comment by aquynh** [comment]
awesome, looks forward to the paper. good luck with your submission!

**Comment by syreal17** [comment]
Finally included [the paper](Cardinal-Malware2016Paper.pdf). We went to Malware 2016 in October!
